version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./model:/model

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "7860:7860"
    environment:
      - API_BASE_URL=http://api:8000/predict
    depends_on:
      - api
    volumes:
      - ./app:/app
      - ./model:/model
      - ./assets:/assets
